name: e_commercial_app
description: Professional_ECOMMERCE_APP_Flutter_2024_BACKEND_FIREBASE

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
#---------------------------PACKAGES---------------------------#
dependencies:
  flutter:
    sdk: flutter

  # UTILITY PACKAGES
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.1.2
  flutter_native_splash: any

  # ICONS:
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State_Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # FireBase
  firebase_core: ^3.2.0
  firebase_auth:
  cloud_firestore:
  google_sign_in: ^6.2.1
  firebase_storage: ^12.1.1
  cached_network_image: ^3.3.1


  #---------------------------PACKAGES_END---------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #---------------------------LOCAL_ASSETS---------------------------#
  assets:
   - assets/logos/
   - assets/images/user/
   - assets/icons/payment_methods/
   - assets/images/on_boarding_images/
   - assets/images/animations/
   - assets/icons/brands/
   - assets/icons/categories/
   - assets/images/banners/
   - assets/images/products/



    #---------------------------FONTS---------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

