// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdZTA26qSd1idCX_RzzkEGvEl9xT4__aA',
    appId: '1:694772331826:web:a8b0ef0c2dbe57d353532b',
    messagingSenderId: '694772331826',
    projectId: 'ecommerceapp-68573',
    authDomain: 'ecommerceapp-68573.firebaseapp.com',
    storageBucket: 'ecommerceapp-68573.appspot.com',
    measurementId: 'G-QZD5WCWPPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_yw8IfOu0mOED7upz9BhNuDra7dEpblY',
    appId: '1:694772331826:android:8b40e70c8dc1a9c553532b',
    messagingSenderId: '694772331826',
    projectId: 'ecommerceapp-68573',
    storageBucket: 'ecommerceapp-68573.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjDiDrPuC7b2rpywLSAsIQDqF0Hm6W7SY',
    appId: '1:694772331826:ios:89d229beb604c7b253532b',
    messagingSenderId: '694772331826',
    projectId: 'ecommerceapp-68573',
    storageBucket: 'ecommerceapp-68573.appspot.com',
    androidClientId: '694772331826-rv6dml6jcbp6lvejqi04tspf3pf2h15d.apps.googleusercontent.com',
    iosClientId: '694772331826-p8phj8lpidn04hkp1k7ropn7jqn4ek9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommercialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjDiDrPuC7b2rpywLSAsIQDqF0Hm6W7SY',
    appId: '1:694772331826:ios:89d229beb604c7b253532b',
    messagingSenderId: '694772331826',
    projectId: 'ecommerceapp-68573',
    storageBucket: 'ecommerceapp-68573.appspot.com',
    androidClientId: '694772331826-rv6dml6jcbp6lvejqi04tspf3pf2h15d.apps.googleusercontent.com',
    iosClientId: '694772331826-p8phj8lpidn04hkp1k7ropn7jqn4ek9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommercialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdZTA26qSd1idCX_RzzkEGvEl9xT4__aA',
    appId: '1:694772331826:web:de8deb13203f7d8253532b',
    messagingSenderId: '694772331826',
    projectId: 'ecommerceapp-68573',
    authDomain: 'ecommerceapp-68573.firebaseapp.com',
    storageBucket: 'ecommerceapp-68573.appspot.com',
    measurementId: 'G-G9030VH4CE',
  );

}